### Get all user

GET http://localhost:3000/api/v1/users
content-type: application/json

### Register user
POST  http://localhost:3000/api/v1/users/register
content-type: application/json

{
    "email": "van@test.com",
    "password": "test1234",
    "firstName": "Van",
    "lastName": "Nguyen"
}

### Login user
POST  http://localhost:3000/api/v1/users/login
content-type: application/json

{
    "email": "van@test.com",
    "password": "test1234"
}

### Logout user
GET  http://localhost:3000/api/v1/users/logout
content-type: application/json

### Get current user
GET  http://localhost:3000/api/v1/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwNzU4NzUsImV4cCI6MTY4OTEzNTg3NX0.qj5_0oYrN7h8IzOelOuNOcWz0Zv9RFZa73JVgTOBdtE

### Update user
PATCH  http://localhost:3000/api/v1/users/1
content-type: application/json

{
    "firstName": "Chinh",
    "lastName": "Tuyet"
}

### Delete user
DELETE  http://localhost:3000/api/v1/users/5
content-type: application/json

### Test user
GET  http://localhost:3000/api/v1/users/test
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTY4OTAwMjIyNCwiZXhwIjoxNjg5MDYyMjI0fQ.CssyCNSLU7QeOGmWPa2CVsHH6m3HTU5cKs41k7m3dNE
