### Get all user

GET http://localhost:3000/api/v1/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoidmFuQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjEsIm5hbWUiOiJBRE1JTiJ9XSwiaWF0IjoxNjg5MjI1OTI5LCJleHAiOjE2ODkzMTIzMjl9.rzNheXII_meLAe9VTmOW8NiLx7dyYRZtlI5btsrnJ_s


### Register user
POST  http://localhost:3000/api/v1/users/register
content-type: application/json

{
    "email": "testskill2@test.com",
    "password": "test1234",
    "firstName": "testskill",
    "lastName": "Nguyen",
    "skills": ["HTML", "CSS", "JavaScript"]
}

### Login user
POST  http://localhost:3000/api/v1/users/login
content-type: application/json

{
    "email": "van@test.com",
    "password": "test1234"
}

### Logout user
GET  http://localhost:3000/api/v1/users/logout
content-type: application/json

### Get current user
GET  http://localhost:3000/api/v1/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6InRlc3Rza2lsbEB0ZXN0LmNvbSIsInJvbGUiOlt7ImlkIjozLCJuYW1lIjoiSk9CX1NFRUtFUiJ9XSwiaWF0IjoxNjg5MjM4NjI5LCJleHAiOjE2ODkzMjUwMjl9._FSB0bUoUHEh3dza-E1m7-J9Bw9w8XIwRaQBqRDq-7A

### Update user (firstname, lastname, skills)
PATCH  http://localhost:3000/api/v1/users/12
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoidmFuQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjEsIm5hbWUiOiJBRE1JTiJ9XSwiaWF0IjoxNjg5MjM4NzgyLCJleHAiOjE2ODkzMjUxODJ9.NacFHIFRwMGDaFahVV-3QHiYzJN4E4cHFAWDnEBmIAQ

{
    "firstName": "Test",
    "lastName": "Tuyet",
    "skills": ["HTML", "CSS", "Reactjs"]
}

### Delete user
DELETE  http://localhost:3000/api/v1/users/5
content-type: application/json

### Get all user
GET  http://localhost:3000/api/v1/users?skill=HTML
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoidmFuQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjEsIm5hbWUiOiJBRE1JTiJ9XSwiaWF0IjoxNjg5MjM3OTY1LCJleHAiOjE2ODkzMjQzNjV9.LPCoLmnh3MDLm_1OB2D5m96zIbTaODXq2zFFWmTCNyg
