### Get all user

GET http://localhost:3000/api/v1/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoidmFuQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjIsIm5hbWUiOiJIUiJ9XSwiaWF0IjoxNjg5MTc3NzcyLCJleHAiOjE2ODkyMzc3NzJ9.UQqKFH9wu5TJzknF4hNiDqvaCkyznRnUBazaBDiTu60


### Register user
POST  http://localhost:3000/api/v1/users/register
content-type: application/json

{
    "email": "khang@test.com",
    "password": "test1234",
    "firstName": "khang",
    "lastName": "Nguyen"
}

### Login user
POST  http://localhost:3000/api/v1/users/login
content-type: application/json

{
    "email": "van@test.com",
    "password": "test1234"
}

### Logout user
GET  http://localhost:3000/api/v1/users/logout
content-type: application/json

### Get current user
GET  http://localhost:3000/api/v1/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtoYW5nQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjMsIm5hbWUiOiJKT0JfU0VFS0VSIn1dLCJpYXQiOjE2ODkxNzc5NjksImV4cCI6MTY4OTIzNzk2OX0.seRFy2pZmQ-uv4Xi_LwxAaoh4GL8E-UjGZx_zWQWcmI

### Update user
PATCH  http://localhost:3000/api/v1/users/1
content-type: application/json

{
    "firstName": "Chinh",
    "lastName": "Tuyet"
}

### Delete user
DELETE  http://localhost:3000/api/v1/users/5
content-type: application/json

### Test user
GET  http://localhost:3000/api/v1/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoidmFuQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjIsIm5hbWUiOiJIUiJ9XSwiaWF0IjoxNjg5MTc3NzcyLCJleHAiOjE2ODkyMzc3NzJ9.UQqKFH9wu5TJzknF4hNiDqvaCkyznRnUBazaBDiTu60
