### Get all job
GET http://localhost:3000/api/v1/jobs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwNzU4NzUsImV4cCI6MTY4OTEzNTg3NX0.qj5_0oYrN7h8IzOelOuNOcWz0Zv9RFZa73JVgTOBdtE


### Get all job by user id
GET http://localhost:3000/api/v1/jobs/9/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwNzU4NzUsImV4cCI6MTY4OTEzNTg3NX0.qj5_0oYrN7h8IzOelOuNOcWz0Zv9RFZa73JVgTOBdtE


### Create Job
POST  http://localhost:3000/api/v1/jobs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoidmFuQHRlc3QuY29tIiwicm9sZSI6W3siaWQiOjIsIm5hbWUiOiJIUiJ9XSwiaWF0IjoxNjg5MDg2MjM3LCJleHAiOjE2ODkxNDYyMzd9.yW4D4CrurIFv_lozlaEnnqdQ1hE4xEpIwyO8o-6fmnk

{
    "title": "Senior Java",
    "generalSummary": "Hire dev to create product for customer",
    "description": "We need a developer",
    "skill": "Java, HTML, CSS",
    "endedAt": "2023-07-30",
    "address": "123 Tan Phu",
    "salary": 3000,
    "type": "FULL_TIME"
}

### Get Job by ID
GET  http://localhost:3000/api/v1/jobs/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwNzU4NzUsImV4cCI6MTY4OTEzNTg3NX0.qj5_0oYrN7h8IzOelOuNOcWz0Zv9RFZa73JVgTOBdtE

### Get Jobs
GET  http://localhost:3000/api/v1/jobs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwNzU4NzUsImV4cCI6MTY4OTEzNTg3NX0.qj5_0oYrN7h8IzOelOuNOcWz0Zv9RFZa73JVgTOBdtE

### Update Job
PUT  http://localhost:3000/api/v1/jobs/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwNzU4NzUsImV4cCI6MTY4OTEzNTg3NX0.qj5_0oYrN7h8IzOelOuNOcWz0Zv9RFZa73JVgTOBdtE

{
    "title": "Senior ReactJS",
    "generalSummary": "Hire dev to create product for customer",
    "description": "We need a developer",
    "skill": "JavaScript, HTML, CSS",
    "endedAt": "2023-07-30",
    "address": "123 Tan Phu",
    "salary": 1500,
    "type": "PART_TIME"
}

### Delete Jobs
DELETE  http://localhost:3000/api/v1/jobs/7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiaHJAdGVzdC5jb20iLCJyb2xlIjpbeyJpZCI6MiwibmFtZSI6IkhSIn1dLCJpYXQiOjE2ODkwODQyMjMsImV4cCI6MTY4OTE0NDIyM30.jEx2dxC1zGi_u6sxaouKJvTGlAIyYb0nKlsVR15NPiI
